### ISSUE TITLE
403: Forbidden (Error)

### ISSUE THREAD

**Issue by AsemK** [mohan3d/arabic-toons-downloader#5]
Interesting work
I am trying to use this package with no success :(
```
python3 downloader.py series http://www.arabic-toons.com/katoli-1429574635-13962.html
Traceback (most recent call last):
  File "downloader.py", line 241, in <module>
    main()
  File "downloader.py", line 233, in main
    downloader.download_series(args.get('<series_url>'),
  File "downloader.py", line 189, in download_series
    self._download_video(episode_url)
  File "downloader.py", line 171, in _download_video
    self._stream_downloader.download(stream_url, filepath)
  File "downloader.py", line 117, in download
    self._download(url, filepath)
  File "downloader.py", line 127, in _download
    segments = self._get_segments(url)
  File "downloader.py", line 140, in _get_segments
    return m3u8.load(url, headers=self.session.headers).segments.uri
  File "C:\Users\asemk\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\m3u8\__init__.py", line 46, in load
    content, base_uri = http_client.download(uri, timeout, headers, verify_ssl)
  File "C:\Users\asemk\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\m3u8\httpclient.py", line 27, in download
    resource = opener.open(uri, timeout=timeout)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.2800.0_x64__qbz5n2kfra8p0\lib\urllib\request.py", line 531, in open
    response = meth(req, response)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.2800.0_x64__qbz5n2kfra8p0\lib\urllib\request.py", line 640, in http_response
    response = self.parent.error(
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.2800.0_x64__qbz5n2kfra8p0\lib\urllib\request.py", line 569, in error
    return self._call_chain(*args)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.2800.0_x64__qbz5n2kfra8p0\lib\urllib\request.py", line 502, in _call_chain
    result = func(*args)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.2800.0_x64__qbz5n2kfra8p0\lib\urllib\request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: Forbidden
```
Can you solve this?
A nice feature to add would be error handling.

**Comment by mohan3d** [comment]
@AsemK Thanks for your suggestion, will be added in the future. 

That means they changed something on their side and I need to update accordingly. I will be troubleshooting and fix it shortly.

**Comment by mohan3d** [comment]
Hey @AsemK Please take a look into [ui-updates branch](https://github.com/mohan3d/arabic-toons-downloader/tree/feat/ui-updates) and let me know if you have further issues.

I will be testing a combination of series and movies before merging this one.
